### ISSUE TITLE
Top margin is not consistent in 3.1.2 version

### ISSUE THREAD

**Issue by LinePersson** [guideguide/support#103]
Dear GuideGuide team, 

I am using Adobe CC2014 and just discovered that the top margin is not consistent depending on the marked (M) distance. In the 2.1.4 version which I used for my CS6 it worked perfectly. 
I am always using top margin 260px as a standard distance, but since using the latest version of GuideGuide the discance differs a lot:
![skarmavbild 2015-01-19 kl 12 25 25](https://cloud.githubusercontent.com/assets/10597102/5799792/c985865a-9fd6-11e4-89c2-e5279e599dc2.png)

My settings:
![skarmavbild 2015-01-19 kl 12 30 16](https://cloud.githubusercontent.com/assets/10597102/5799810/fae15f6c-9fd6-11e4-9aa0-0f6b33df2fca.png)

I think its a bug, because I had the same settings in 2.1.4 and the margin was always correct then.

Thanks in advance GuideGuide team :)

**Comment by cameronmcefee** [comment]
Hi @LinePersson,

Can you please provide an example of the incorrect guides? Can you also clarify what "marked (M) distance" means? There are no guides in the image you attached so I'm a little confused.

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
