### ISSUE TITLE
Cannot install in Mac PS 2014 CC

### ISSUE THREAD

**Issue by dfwilson** [guideguide/support#104]
Each time I try to install the guide in PS 2014 CC via the Adobe extension Manager I get the message that it requires PS 12 or higher. I am using the latest version on my Mac. What is going on and how do I correct it?

**Comment by gavd8** [comment]
I have the same problem :(

**Comment by sardari-shervin** [comment]
same problem here :/

**Comment by cameronmcefee** [comment]
Hi all,

Be sure you're launching the CC version of the Extension Manager, that you can see Photoshop CC 2014 in the application list on the side of the Extension Manager, and that the Extension Manager is on the latest version. Typically it's one of those three things not being correct that causes that error.

![monosnap 2015-01-23 11-13-12](https://cloud.githubusercontent.com/assets/72919/5880912/f91a9f82-a2f0-11e4-8e07-d946c78debbc.jpg)

**Comment by sardari-shervin** [comment]
hello it was truly an update problem 
My soft was update but i think it was not correctly installed so i recommend for those who have the same problem to unistall the soft and  re-install and re-update it in command line to be sure there is no conflict. 

Thanks to help me solving this prob 
S.
