### ISSUE TITLE
JavaScript Prompt - file:/// popup when behind proxy

### ISSUE THREAD

**Issue by AdminHam** [guideguide/support#105]
Guideguide 3.1.2
Photoshop CC 2014 (15.2.2)
Auto proxy discovery, or manual proxy set with credentials

When attempting to load the guide guide panel for the first time I get the following popup:
![screen shot 2015-01-28 at 11 10 12 am](https://cloud.githubusercontent.com/assets/10732042/5928215/402b3f62-a6de-11e4-9e13-9b0da17142cd.png)
JavaScript Prompt - file:/// 
SERVER CREDENTIALS REQUIRED. Please enter your username:

This prompt always comes up twice, and succeeds on loading panel content if I enter: domain\username
else the panel content fails to load.
Prompt pops up on each new launch of Photoshop.

Is there a way of caching the extension content so this popup doesn't occur?

**Comment by pmilez** [comment]
... and the password popup dialogue box shows my password entry in plain text.

**Comment by cameronmcefee** [comment]
Hello,

I'm unclear as to what's causing the prompt. Are you running on some sort of network that requires logging in to access the internet? The only thing that I could see that would cause that is that GuideGuide checks for updates when it starts, so if you need to log into something to use the internet that might explain it.

> Is there a way of caching the extension content so this popup doesn't occur?

This is not possible at this time.

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
