### ISSUE TITLE
PS CC, GG 3.1.2

### ISSUE THREAD

**Issue by AliceSagara** [guideguide/support#106]
The previous version did not respond to a click.
3.1.2 does not start.
help :(

![111](https://cloud.githubusercontent.com/assets/10754656/5954675/97a13b7a-a7ab-11e4-8d2b-36a120cbba79.png)

**Comment by mrandrason** [comment]
same problem with me...please help..

**Comment by cameronmcefee** [comment]
Hello,

Can you confirm which versions of Photoshop and the Extension Manager you are using? This issue usually happens with out of date versions of one of the two.

![monosnap 2015-02-05 15-54-43](https://cloud.githubusercontent.com/assets/72919/6071839/5106d68a-ad4f-11e4-8c8c-6b5952c60cc3.jpg)

![monosnap 2015-02-05 15-52-04](https://cloud.githubusercontent.com/assets/72919/6071808/f33b8d48-ad4e-11e4-8905-d71fd622d160.jpg)

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
