### ISSUE TITLE
row height with pt

### ISSUE THREAD

**Issue by burakk** [guideguide/support#108]
Hi, 

I have an A4 sized document with 200 ppi resolution, when i set row height to 12pt to create a grid the row heights automatically created by guideguide is strange. In that document an 12pt height selection area is almost three times height of guideguide row height?

Am i doing smt wrong?

**Comment by cameronmcefee** [comment]
Hi @burakk 

GuideGuide currently treats points as 1:1 with pixels. If you were to change your selection to be pixels you'd likely see that the rows are 12px tall.

I don't personally work with print much and haven't measured in points in memorable history. What is the conversion metric for points? I'd like to include that in future versions.

**Comment by cameronmcefee** [comment]
Closing as stale
