### ISSUE TITLE
little help please

### ISSUE THREAD

**Issue by artisttoolbox** [guideguide/support#109]
sorry, i feel like a noob. i have an older version at home and i figured it out just fine... but your latest version, i can't do it.

i want guides put in showing my bleed, trim and safety areas for designing print ads and posters, postcards etc.

For example. if my final size postcard is 4"x6" i'll create my document 4.25 x 6.25 so i can have an 8th of an inch bleed on all 4 sides. So i need my guides an 8th of an inch away from all 4 edges, and then another set of guides 

so 8 guides total.  This has to be independent of what size my original document is.  i hope i've described this correctly!

have no clue how i got it to work in the older version! :(

**Comment by cameronmcefee** [comment]
Hi @artisttoolbox,

To do 1/8" bleeds and trims, you should be able to put `.125in, .125in` in each of the margin fields and then hit the "add guides" button. That should do it, but if not, let me know.

If you want to *also* include a margin, just add your margin to the comma separated list. For example, a half inch margin in addition to your bleeds and trims would look like `.125in, .125in, .5in`

**Comment by artisttoolbox** [comment]
hey, really appreciate the feedback, but i wanted to make a set, where i can just click a button and no matter what size my graphic is, it will automatically make my trim and safety lines. i know it can be done because my guide guide on my home computer has it. i don't remember how i did it. is there a preferences file i can just copy and move to my work computer?

**Comment by cameronmcefee** [comment]
@artisttoolbox if you're using GuideGuide 3 on both computers, yes you can export/import your sets. You'll find those options under the gear icon menu.

![guideguide 2015-02-18 11-03-43](https://cloud.githubusercontent.com/assets/72919/6254482/d1ba2bb6-b75d-11e4-8a05-ed8aa2d87cdc.jpg)

Unfortunately, if your versions of GuideGuide are not both GuideGuide 3, you won't be able to exchange sets between them at the moment.

Alternatively, if you want to save a set with bleed/trims, use the instructions above, but click the Add Set button to save it.

![guideguide 2015-02-18 11-04-38](https://cloud.githubusercontent.com/assets/72919/6254498/f1c9fa58-b75d-11e4-8fcd-977d56e127f6.jpg)

**Comment by cameronmcefee** [comment]
Closing as stale
