### ISSUE TITLE
Update the GUI?

### ISSUE THREAD

**Issue by dougdraws** [guideguide/support#111]
Total non-issue, but.....when are you guys going to update the GUI? I wrote and asked about this a while ago when I noticed the screenshots of GG were not the same as the actual extension I downloaded and used. I think someone responded, but I don't remember.

Anyway, it obviously hasn't been updated. I know it's completely anal of me, but I'm almost ashamed having that 1960's-looking thing in my two-thousand dollar program.

**Comment by cameronmcefee** [comment]
Hi @dougdraws,

Thanks for the question. It'll ship when it's ready :D GuideGuide's a side project so it moves at the pace my life allows.
