### ISSUE TITLE
Guides from an Object

### ISSUE THREAD

**Issue by clarkedesign** [guideguide/support#112]
Photoshop CC 2014 introduces a new 'Guide from Shape' option.
Would be great to have a button on the panel that did the same.

Also I've seen a couple of other plugins that create guides based on a selected object.
Top guides, bottom guides, side guides, centre of object guides, crosshair centre etc....

Would be nice to see these features as well

![capture](https://cloud.githubusercontent.com/assets/3541228/6218998/31806814-b61c-11e4-95e1-51b001bd92c7.PNG)

**Comment by cameronmcefee** [comment]
Hi @clarkedesign,

GuideGuide has always been able to do this based on a selection (rather than a shape so you don't have to delete anything). I'm pretty sure Adobe got the idea from me :wink:.
