### ISSUE TITLE
guideguide showing no contents

### ISSUE THREAD

**Issue by estabij** [guideguide/support#114]
Hi,
I just downloaded 3.1.3-guideguide.zxp and installed it for Photoshop CC 64 bit using the extension manager. However when I open the plugin in Photoshop I see an empty plugin. It is white and has no contents when I open it in Photoshop.
Best regards,
Erik

**Comment by estabij** [comment]
![guideguide-empty](https://cloud.githubusercontent.com/assets/2077404/6263693/66b7a2f8-b81b-11e4-8283-797091b327f5.jpg)

**Comment by cameronmcefee** [comment]
Hi @estabij,

Can you confirm Photoshop and the Extension Manager are up to date?

![monosnap 2015-02-19 12-16-21](https://cloud.githubusercontent.com/assets/72919/6275067/27aab756-b831-11e4-871e-6170bfe8cae5.jpg)
![monosnap 2015-02-19 12-16-55](https://cloud.githubusercontent.com/assets/72919/6275071/39e1e8e0-b831-11e4-9367-8f790d6a3571.jpg)

**Comment by estabij** [comment]
The problem is with:
Extension Manager is version 7.2.1.6.
Photoshop is 14.0 x64.

I have updated to the newest versions and now it works. Thanks!

**Comment by cameronmcefee** [comment]
Glad to hear it!
