### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by beelie** [guideguide/support#116]
Hi I am wondering how do you download this into adobe? I use adobe extesnions manager and pushed installed but the icons in guide guide are greyed out and they will not allow me to press them?

**Comment by cameronmcefee** [comment]
Hi Beelie,

Can you provide a screenshot of what you're describing?

**Comment by beelie** [comment]
Here is the screen shot

**Comment by beelie** [comment]
Its not letting me screen shot
 /Users/hersheyhoopz/Desktop/Screen Shot 2015-02-24 at 5.45.02 PM.png

**Comment by beelie** [comment]
But when I go into adobe extensions manager then i go to photo shop and hit the file none it will not let me select any of the option whats the process of installing this?

**Comment by cameronmcefee** [comment]
The process to install is:

1. Download the latest file from http://guideguide.me/, currently *3.1.3-guideguide.zxp*.

2. Double click the .zxp file. Adobe Extension Manager will launch and ask you if you would like to install GuideGuide. Follow the steps to install.

3. Launch Photoshop. Go to Window > Extensions > GuideGuide.

Be sure the version of the Extension Manager matches your version of Photoshop. For example, if you have Photoshop CC or CC 2014, be sure you're launching the CC Extension Manager.

**Comment by beelie** [comment]
Okay thank you much I just downloaded it
