### ISSUE TITLE
Quick guides - opens Photoshop Preference window 

### ISSUE THREAD

**Issue by edumesnil** [guideguide/support#117]
Every time I clic on the quick midpoint guide button, it opens the preference window on Units & Rulers over and over again before placing the guide on the canvas.

Latest version of Photoshop CC 2014

**Comment by edumesnil** [comment]
I remove the extension and reinstalled it and now it works fine..

**Comment by cameronmcefee** [comment]
Glad to hear it's working. That's a very weird thing to experience. I'll have to keep it in mind in case I hear about it again.
