### ISSUE TITLE
Failed to Install the Creative Suite Extension

### ISSUE THREAD

**Issue by mehedijaman** [guideguide/support#122]
Hi. I am facing problem installing GuideGuide.
When I am attempting installing it shows me this message:
Failed to install the creative suite Extenstion
Make sure the Manifest.xml of this extension is valid and the external Manager recognizes at least  one product which the extension support. The extension will not be installed.

**Comment by cameronmcefee** [comment]
Hi @mehedijaman,

That error usually happens in a couple cases:

1. If you're trying to install it into the CC Extension Manager for Photoshop CC 2014, your extension manager is probably out of date. The latest is 7.3.2.39

  ![screen shot 2015-01-23 at 11 12 55 am](https://cloud.githubusercontent.com/assets/72919/6722366/dd33ea9c-cd95-11e4-9a11-384ac8c8ff02.jpg)

2. If you're trying to install it in another version be sure that the version of the Extension Manager you launch to install matches your version of Photoshop, and that you see photoshop in the sidebar.

  ![monosnap 2015-03-18 17-47-03](https://cloud.githubusercontent.com/assets/72919/6722450/dea89bba-cd96-11e4-9019-7bd9a2c0d809.jpg)

**Comment by hannesgrebin** [comment]
You have to apply the update-patch — the normal installer would install the old version
https://www.adobe.com/exchange/em_updates/
