### ISSUE TITLE
PS CC 2014 install issue

### ISSUE THREAD

**Issue by GinaSwindler** [guideguide/support#123]
I have PS CC 2014 on my MacBook pro retina and for some reason when I try to install guideguide 3.1.3 in my adobe extension manager, I get a message that reads "the extension cannot be installed, it requires Photoshop 12 or greater" (see screen shot). Any help would be appreciated! Thanks in advance

![screen shot 2015-04-01 at 10 11 17 am](https://cloud.githubusercontent.com/assets/11755607/6942821/1720bfec-d858-11e4-914c-9b22f2fb2da8.png)

**Comment by lance1572** [comment]
I got this error as well. You should update PS and the CC application itself. That helped me.

**Comment by AUusa** [comment]
I am having the same problem as Gina. I have updated PS and the extensions manager and I am still getting the same problem. Any ideas?
I even downloaded an older version of the GuideGuide and it gave me the same message.

**Comment by cameronmcefee** [comment]
@GinaSwindler, if you look in the left hand column (through the dark overlay) you'll note Photoshop doesn't appear to be in the list. That's what is causing the error. As to why it's not in the list, that part is unclear. That's an issue you will have to resolve on your own or with Adobe, unfortunately.

@AUusa can you provide a screenshot of your particular case?

**Comment by lance1572** [comment]
@AUusa...did you update Creative Cloud Application too? Not just PS and the Extension Manager. Doing all three helped me. FYI Hope it works out for ya

**Comment by cameronmcefee** [comment]
Closing as stale
