### ISSUE TITLE
Guide Guide Single Line Margin

### ISSUE THREAD

**Issue by zerimar3** [guideguide/support#127]
I'm using Guide Guide to set up bleeds for print files. Is there a way to set it so that there are only single guides around the edge at 0.125 in without having additional guides to the document bounds?

Currently showing: 

| 0.125in | ~ | 0.125in | ( vlp, | ~ )
| 0.125in | ~ | 0.125in | ( hlp, | ~ )

Thanks for the help!

**Comment by cameronmcefee** [comment]
Hi @zerimar3,

Yep! The `|` character says "put a guide here" so simply remove the edge `|`s and you'll get what you need.

```
0.125in | ~ | 0.125in ( vlp, | ~ )
0.125in | ~ | 0.125in ( hlp, | ~ )
```

**Comment by zerimar3** [comment]
Fantastic @cameronmcefee! I had copied that from the Custom panel after having plugged in the sizes on the Grid panel. Tried other variations to no avail but this worked, thanks a million!
