### ISSUE TITLE
Frequently used grid sets integrated

### ISSUE THREAD

**Issue by Phreakzor** [guideguide/support#128]
Hi there, 

I use your extension almost every single day and I was wondering if you can integrate a set for 1200px and 960px grid? 

I know I can make it by myself and save it as custom set, but sometimes the extension crashes and I lose my custom sets, so I have to make them again. Is there any possibility to make the frequently used grids as an integrated feature? That would be much appreciated!

**Comment by cameronmcefee** [comment]
Hi @Phreakzor,

To be honest, I think it's more important to solve the crash memory loss issue. That shouldn't ever happen. From the way GuideGuide works, if a set is saved, a crash should not delete it. Given that, I think there are two separate issues to investigate.

First things first, do you have the latest version (3.1.4) from http://guideguide.me/ ?

Can you let me know what version of Photoshop you're using?

**Comment by Phreakzor** [comment]
First of all, yes, I have the latest version of your extension. Secondly, I'm using Photoshop CC. 

There may be many other reasons why the extension crashes, other than the extension itself (pirated OS, Photoshop - just saying - please delete this part). I don't know how you can handle this, but from the UX point of view, I think that the feature of having the default used grids integrated in the extension are extremely useful. Think about the fact that I use the extension on my PC and I have the custom sets saved, but a client/friend/person asks me at some point to help them with a website regarding its responsiveness and I have help them using their PC. If they don't have the extension, I will install it for them and I would have to create the custom set again. This is time consuming and not always you do have the time to do that. Maybe I forget to save the set and they would have to do it again. Maybe I re-install Photoshop, and I would have to do it again. 

I think that it easier and more convenient to have this feature already in the extension. Maybe it's just me.

Create some personas and try to figure out what are the features that will help almost every user of it regardless of their experience in Photoshop or your extension. This will help you a lot.

Please take all of the above as my personal opinion. You can ignore it if you want. I don't want to make you feel uncomfortable by it. All I want is to help as much as I can.

**Comment by cameronmcefee** [comment]
Thanks @Phreakzor, I do think your idea is a good one. I'll keep it in mind.
