### ISSUE TITLE
Not keyboard friendly (Enter / Return, Tab) — UX issue

### ISSUE THREAD

**Issue by TheDevo** [guideguide/support#129]
Hey,

First off, I don't want to sound unappreciative, because I am madly in love with this plugin, I'm surprised Adobe hasn't thrown a bunch of dollars in your face for it.

ENTER / RETURN & TAB:
(previously)
1. Enter values into input fields ...
2. ... using the TAB key to jump from one to the next (Shift+Tab to go back)
3. Hit enter once ready, to see the grid be made

(now)
1. Enter value into input field
2. Hit tab to jump to next input field but Ps UI is hidden instead
3. Using mouse to switch between input fields, I enter each value
4. Hitting enter won't do a thing, have to manually click "Make grid" on panel

I'm sure anyone who has worked with grids and knows the process it takes to design the perfect grid for the given canvas and the desired composition can say that this can get very frustrating.
Especially since I got so used to the fluid, barrier-free workflow that the previous version allowed.

Can you please do something about this? It's sounds insignificant, but in the span of a year, this could save designers hours.

Thanks in advance!

**Comment by cameronmcefee** [comment]
Hi @TheDevo,

Sadly this is a PS bug, and all extensions suffer from it. The good news is that they've fixed it in the next major (forthcoming) release. Just hang tight and update when you have the chance and all should be well.
