### ISSUE TITLE
toggle visibility in version 2.1.4?

### ISSUE THREAD

**Issue by gonegone** [guideguide/support#131]
hello,
i've just installed this version, and am not finding a way to turn off the guides without clearing them.
thanks in advance for your help!

**Comment by cameronmcefee** [comment]
Hi @gonegone,

GuideGuide 2.1.4 doesn't support toggling guide visibility. You'll unfortunately have to toggle it yourself via the standard Photoshop controls if you don't wish to upgrade to the latest versions of GuideGuide.
