### ISSUE TITLE
Grid not centered - GuideGuide 3.1.4 - Photoshop CC (2014)

### ISSUE THREAD

**Issue by mercedssss** [guideguide/support#132]
Hi. I just installed GuideGuide 3.1.4 and tested setting up a grid. The resulting grid is off center as displayed in the attached image. Is this a bug or am I doing something wrong? Please advise. Thanks.

![guideguide issue](https://cloud.githubusercontent.com/assets/12723272/7950630/c30db0aa-096b-11e5-90e5-9905d7f43355.png)

**Comment by cameronmcefee** [comment]
Hi @mercedssss,

By default, GuideGuide is left aligned when the total grid is skinnier than the document. You can adjust this setting by clicking the gear icon, then picking "center" from the Horizontal Position dropdown.

Also of note, it looks as though you may have been trying to do left/right margins, but entered the left margin in the bottom margin field. I mention this just in case you felt like that was an unexpected result.

**Comment by mercedssss** [comment]
Hi @cameronmcefee 

Thanks for clarifying on the alignment issue. Yes I was trying to do left/right margins but realized that I had erred after doing the screenshot...hence why I didn't mention it. Appreciate the quick follow up.
