### ISSUE TITLE
PS 2015 CC: doesn't working grid for selection.

### ISSUE THREAD

**Issue by qlkv** [guideguide/support#136]
When I want to make grid for selected area — it doesn't working as it was before. Guides creating for document, not for selected area. Please fix it.

**Comment by cameronmcefee** [comment]
Hi @qlkv,

I'm sorry to hear you're experiencing issues. I can't reproduce the problem (it works fine for me). Can you provide steps for how to reproduce the problem?

**Comment by WilliamChamberlin** [comment]
I am having a similar problem but with art boards (CC 2015). I can't select one art board to create a grid on, it encompasses the entire document.

**Comment by cameronmcefee** [comment]
I posted a new version this morning that should hopefully solve these issues: http://guideguide.me/ GuideGuide will now create guides based on your selected artboard.
