### ISSUE TITLE
CC2015 – Prev Installed but not showing in Extensions

### ISSUE THREAD

**Issue by MissLeliel** [guideguide/support#137]
I just upgraded to CC2015, and my previously installed GuideGuide from CC 2014 was showing in the Extension Manager, but not in the Window > Extensions menu, so I'm unable to use it. I tried removing it and reinstalling from the ZXP file but that didn't work.

I looked at the instructions for a manual install using the 2015 zip, but the folder "CEP" does not exist in my "Application Support > Adobe" folder.. Do I need to I create it?

**Comment by cameronmcefee** [comment]
Hi @MissLeliel,

I'm sorry to hear of the trouble. You should not need to create a CEP folder, it will already be there. If it is not there, that's indicative of another problem, though I'm not sure what.

Can you confirm that you're in the main `Library` folder, and not your personal `Library` folder? To be sure, you can open the correct folder by running the following command in the Terminal (If you're not familiar with the command line, note the slash before the space in the file name):

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by MissLeliel** [comment]
Hi Cameron,

That worked! I was looking in my user library folder, but after copying your zip contents to the location you gave, it's working like a charm. Thanks! I love GuideGuide – it's a critical part of my responsive design workflow so I was about to panic, haha!

**Comment by cameronmcefee** [comment]
:metal: I'm glad to hear you got it working!
