### ISSUE TITLE
Guide Guide v3.1.4 install issue on CC2015

### ISSUE THREAD

**Issue by elizma-rt** [guideguide/support#140]
Hi please help.

I have followed your install steps but some folders i do not have please contact me to install this extention

**Comment by cameronmcefee** [comment]
Hi @elizma-rt,

Can you explain further what you mean? What folders do you not have?

**Comment by carrielee8** [comment]
Hello. I am trying to install for Photoshop CC2015. My Extension Manager says it has been installed, yet when I go into Photoshop> WIndows> Extensions it is not there..?

**Comment by carrielee8** [comment]
Also, I have tried installation both ways, manually and thru the Extension manager...

**Comment by cs2art** [comment]
It took me a little while to figure out what I was doing wrong but here's the solution.  After you unzip the 3.2.0-guideguide-cc2015.zip, open up the GuideGuide folder and drag the nested GuideGuide folder (above the readme.txt) into the extensions folder. I initially just dragged the entire folder in and that doesnt work.  Hope this helps...  I love me some guideguide!

**Comment by carrielee8** [comment]
Whoo Hoo!! Yes that worked! Thank you very much!

—
Carrie Aipperspach
Design

Upside Collective
80 State Street
Albany NY 12207
www.upsidecollective.com
518-370-0108

**Comment by cameronmcefee** [comment]
Ah, yep, that would cause the problem. I should figure out a clearer way to communicate that in the installation instructions. Thanks for the feedback!
