### ISSUE TITLE
Unable to install GuideGuide on Ps CC 2015

### ISSUE THREAD

**Issue by DianaCa** [guideguide/support#141]
I can't seem to find the CEP folder they are talking about in the instructions.

**Comment by cameronmcefee** [comment]
Hi @DianaCa,

Assuming you do in fact have CC 2015 installed (the folders won't be there if not), and that you're using OSX, then my guess is that you're looking in you personal library folder rather than the system one. Try running the following command in the terminal to open the correct folder:

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by DianaCa** [comment]
Thanks for your quick response @cameronmcefee and for the command. It worked!

**Comment by cameronmcefee** [comment]
:+1: Glad to hear it. I'm going to close this now, but feel free to reopen if you have further issues.
