### ISSUE TITLE
GuideGuide not showing under "Extensions" in Photoshop 2015

### ISSUE THREAD

**Issue by jimmylep** [guideguide/support#142]
Just upgraded to PS 2015 and GuideGuide did not show up under "Extensions.". Tried downloading new version of it and copying it over the old one, but still doesn't show up.

Am I the only one with this issue or do others have it?

**Comment by cameronmcefee** [comment]
Hi @jimmylep,

Can you confirm that your folders look like this?

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by jimmylep** [comment]
Thanks for the quick response, Cameron. I had that wrong. I had the main GuideGuide folder there so the actual GuideGuide folder with the files was one level down along with the README (if that makes sense). Totally my bad. Updated that and it works great. So happy to have it back. Thanks!

**Comment by cameronmcefee** [comment]
@jimmylep totally understandable. I've seen a few people do that so I had a hunch your case might be the same. I should figure out a clearer way to name the folders to prevent that.
