### ISSUE TITLE
GuideGuide not installing on Photoshop CC 2015

### ISSUE THREAD

**Issue by addsalt** [guideguide/support#145]
Using latest version of Extension manager (7.3.2.39) and latest update of Photoshop CC 2015. Extension shows as installed but does not show up in Window > Extension.

![screen shot 2015-06-21 at 1 21 46 pm](https://cloud.githubusercontent.com/assets/9367681/8272625/b592e7fe-1818-11e5-8042-53ae1b7d7688.png)

![screen shot 2015-06-21 at 1 22 21 pm](https://cloud.githubusercontent.com/assets/9367681/8272627/c0144132-1818-11e5-8df4-6f71cd871c23.png)

![screen shot 2015-06-21 at 1 22 04 pm](https://cloud.githubusercontent.com/assets/9367681/8272628/c57a5788-1818-11e5-8fba-d3663ca506e0.png)

![screen shot 2015-06-21 at 1 22 35 pm](https://cloud.githubusercontent.com/assets/9367681/8272630/c9895d74-1818-11e5-98c2-32664965184e.png)

Tried following GuideGuide instructions to paste folder into Adobe/CEP/ extensions, but CEP folder doesn't exist inside Adobe folder.

![screen shot 2015-06-21 at 1 23 08 pm](https://cloud.githubusercontent.com/assets/9367681/8272631/cf4672c4-1818-11e5-9117-e3deb7346470.png)

Halp? :(

**Comment by streetevens** [comment]
Please uninstall and delete GuideGuide folder in the extensions folder.
Install again. 
Will be succeed.

**Comment by cameronmcefee** [comment]
Hi @addsalt,

Another user experienced this same issue [here](https://github.com/guideguide/support/issues/143) and found that in their case uninstalling the extension manager resolved the problem.

I also noticed that the library folder you are showing is your personal folder, not the system one. You can run the following command in the terminal to open the correct folder:

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by addsalt** [comment]
@cameronmcefee 

Worked like a charm! Thanks for the tip and the quick response.

**Comment by cameronmcefee** [comment]
:+1: Glad to hear it's working.
