### ISSUE TITLE
Guide Guide doesn't show up on 2015 photoshop CC

### ISSUE THREAD

**Issue by marieyuan43** [guideguide/support#148]
Hello, My guide guide doesn't show up on the latest version of photoshop even through I tried to install the extension. Could you help me with it? I do have dropbox folder but I wasn't sure how it affects the extension. Thank you.

**Comment by cameronmcefee** [comment]
Hi @marieyuan43,

Dropbox will only affect GuideGuide if you have the GuideGuide files *inside* the Dropbox sync folder. This would be a very uncommon issue.

Can you be more specific what you mean by "tried to install the extension"? Are you on Windows or OSX? Did you run into errors? Where did you put it?

**Comment by brwarhol** [comment]
I'm having the same issue as well on CC 2015 on OSX.  I installed it through the extension manager, however, the extension doesn't show in the menu option, yet the extension manager shows it as installed.

**Comment by marieyuan43** [comment]
Hello, Cameron

Thanks for reply. I used it during work so I downloaded the zip file in our work server and installed GuideGuide through the extension manager. After knowing that the extension won't shoes up, I tried uninstall GuideGuide and installed it again. During the process, no error window popped up and it shows installed in the extension manager. I even tried reinstalled Photoshop and extension manager bury it doesn't work. My laptop is Mac OS X.

Before I did have Dropbox that sync some works but it doesn't include the folder with GuideGuide in it.

Thanks again for helping. Hoe there is a way to solve this.

Sincerely 
M

**Comment by cameronmcefee** [comment]
Ah ok. Adobe removed support for the Extension Manager in CC 2015 (I'm not sure why it shows up), so you will need to follow the manual install instructions on http://guideguide.me/

**Comment by marieyuan43** [comment]
Thanks! It works this time now!

Thank you so much. Have a good day.
M

**Comment by cameronmcefee** [comment]
Glad to hear it!

**Comment by marieyuan43** [comment]
Hello, Cameron

This is Marie, whose Guide guide is not showing up again in photoshop CC
2015. I tried the last method you told me, which is following the
instruction on the guide guide link. However, it doesn't show up. I tried
create a CEP folder because I don't have one. somehow guide guide still
doesn't show up.

I am hoping you can help me.  Thank you.

M

**Comment by Soularix** [comment]
Hey I would like to know please did you fix the problem ?

**Comment by cameronmcefee** [comment]
@soularix, yes GuideGuide works fine in CC 2015. If you're experiencing issues, please check out http://guideguide.me/support
