### ISSUE TITLE
Cannot Install GuideGuide (Photoshop CC 2015- Windows 64)

### ISSUE THREAD

**Issue by keithjparks** [guideguide/support#149]
I was attempting to follow your manual instructions for installing guideguide, but the files 'CEP' or 'Extensions' do not exist in my adobe common file.

**Comment by cameronmcefee** [comment]
@keithjparks can you confirm you're looking in the `C:\Program Files (x86)\Common Files\Adobe\` directory (note the x86 part)?

**Comment by cameronmcefee** [comment]
Actually, I noticed you change the title from 32 to 64. The path above is the necessary path for 64. The path for 32 is `C:\Program Files\Common Files\Adobe\CEP\extensions\`

**Comment by keithjparks** [comment]
Yes that's where I'm looking. I've checked about every adobe file on my computer and none of them contain the files 'CEP' or 'extensions. 
![untitled-2](https://cloud.githubusercontent.com/assets/8008543/8321471/19f05cd0-19dc-11e5-9843-a3e95fd9d089.jpg)

**Comment by undavide** [comment]
Hi Keith,
I'd suggest two workarounds:

1) Create yourself the folder "C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\" if it's not already present (in the x86 side of the Program Files) and copy in there the panel.

2) Use the following path instead: C:\Users\<yourUser>\AppData\Roaming\Adobe\CEP\extensions

I'd try #1 first, then if it fails #2 (in case the second path's missing, try creating it).
Let us know!

**Comment by keithjparks** [comment]
Option 1 worked. Thanks for the help! Adding that file path to the C:\program files (x86) actually added that same file that to the Users\appdata\roaming\adobe file path.

**Comment by cameronmcefee** [comment]
Thanks @undavide!

@keithjparks I'm glad to hear that worked for you. I'll keep this solution in mind should I hear of similar reports.
