### ISSUE TITLE
Unable to install GuideGuide in Photoshop CC 2015, OSX

### ISSUE THREAD

**Issue by mikeprecious** [guideguide/support#150]
Tried both install methods (folder moved in to Extensions folder and ZXP file option).

Moving GuideGuide folder with enclosed items to the /Library/Application Support/Adobe/CEP/extensions/ folder did not see GuideGuide show up in Photoshop.

Double clicking the ZXP file opened Adobe Extension Manager. A pop-up reads: This extension can not be installed, it requires Photoshop version 12 or greater.

At this point, I'm unable to get GuideGuide to show up and work in my copy of Photoshop CC 2015. 
![screenshot 2015-06-24 07 41 39](https://cloud.githubusercontent.com/assets/1815165/8329102/a65b0798-1a44-11e5-8fb4-dd35b1456e46.png)

**Comment by cameronmcefee** [comment]
Hi @mikeprecious,

Sorry for the trouble! The fact that the Extension Manager didn't work isn't surprising, it is no longer supported by Adobe. It just happens to work in some cases.

As for the manual install method, are you sure you installed GuideGuide into the *system* Library folder? Most cases of "it doesn't show up" come as a result of trying to install into the *user* Library folder. The following Terminal command will open the correct folder, just to be sure:

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by mikeprecious** [comment]
Hi Cameron,

thanks for the help. I did in fact, I have it in the correct folder. However, a user went on to point out in a subsequent Issue that it’s important to extract the inner GuideGuide folder from the main unzipped parent folder, and move the inner GuideGuide folder to the OS system path you specified. After doing that, it worked.

Kind regards,
Mike

**Comment by cameronmcefee** [comment]
Ah yes, that's been another issue that I need to figure out how to socially engineer. I'm glad to hear it's working for you.
