### ISSUE TITLE
Cant find the CEP folder for Photoshop CC2015 Mac OSX

### ISSUE THREAD

**Issue by LinePersson** [guideguide/support#151]
Hi,

I cant find the "CEP" folder which contains the "Extensions" folder for Photoshop I only find it for Illustrator.. I cant find "/Library/Application Support/Adobe..." so I wonder if that has anything to do with me having adobe creative cloude?  I uninstalled Photoshop and installed it again. Extension Manager cant find Photoshop CC2015 like you saying in your "Read Me" manual. Please what am I doing wrong?

**Comment by cameronmcefee** [comment]
Hi @LinePersson,

Sorry for the trouble!

> Extension Manager cant find Photoshop CC2015 like you saying in your "Read Me" manual.

Adobe removed support for the Extension Manager in CC 2015, so it only "works" in some specific cases. It sounds like unfortunately it doesn't work in your case.

> I cant find the "CEP" folder which contains the "Extensions" folder for Photoshop I only find it for Illustrator

Try running the following command in the Terminal, which will open the correct folder for installation:

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by LinePersson** [comment]
Awesome! It worked, thank you! :D

**Comment by cameronmcefee** [comment]
Glad to hear it!
