### ISSUE TITLE
Photoshop CC 2015. guide guide not showing up despite following install instructions.

### ISSUE THREAD

**Issue by Zachstatler** [guideguide/support#152]
I've installed guideguide exactly as specified in the instructions, however I still cannot access this from photoshop. How can i fix this issue??

**Comment by mattlovaglio** [comment]
@Zachstatler, I had the same issue this morning. But I made a silly mistake.

*Are you sure you dropped in the correct folder?*

Note that after uncompressing the file, the folder name is "GuideGuide". If you open that folder there should be *another folder* labeled "GuideGuide" as well as a read me file. It is **this** folder that needs to be dragged into the "extensions" folder. 

#### This is where the folder goes:

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by Zachstatler** [comment]
The file was in the correct location. The problem was that I had dropped the entire GuideGuide along with the the readme, rather than the nested GuideGuide folder. Everything is working smoothly now. Thank you!

**Comment by cameronmcefee** [comment]
:+1: Glad you got it working, that's definitely another common issue. I need to find a less confusing way to write those installation instructions.
