### ISSUE TITLE
Uneven grids

### ISSUE THREAD

**Issue by brwarhol** [guideguide/support#154]
Hi,

I recently managed to get your app working in CC 2015 on OSX.  However, the extension always, without fail, manages to create uneven grids on the image canvas, no matter what size the image is.  I've even tried adjusting the image size to 1280 and 1440 width with no avail.  What could be the issue?
![uneven](https://cloud.githubusercontent.com/assets/12108576/8341289/e4d75ab0-1a91-11e5-869f-38e329b1b7b8.jpg)

**Comment by cameronmcefee** [comment]
Hi @brwarhol,

What you're experiencing is GuideGuide's grid alignment. The grid you've generated presumably had a fixed width, count, and gutter. Together those make up an exact measurement, one which is smaller than the total width of the document (thus the gap). By default, GuideGuide left aligns the grid, however you can change this setting under the settings (gear) menu to be centered or left aligned, as you please.

**Comment by brwarhol** [comment]
@cameronmcefee,

Do you mean adjusting the "Horizontal position?

**Comment by cameronmcefee** [comment]
@brwarhol that's correct
