### ISSUE TITLE
Not working on Photoshop CC 2015 with Windows

### ISSUE THREAD

**Issue by ghost** [guideguide/support#155]
The first thing is that you have the folders mixed up. The programs x86 folder is for 32bit Windows. There is no x86 folder on 64bit Windows. These two should be the other way around:

Windows 64: C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\
Windows 32: C:\Program Files\Common Files\Adobe\CEP\extensions\

I put the folder where you suggested...

C:\Program Files\Common Files\Adobe\CEP\extensions\GuideGuide

...and it still doesn't show up in Photoshop. It was fine in every version previous to this and I've been using it since CS6.

I am on Windows x64.

Thanks

**Comment by cameronmcefee** [comment]
Hi @Coflash,

I'm sorry to hear about the trouble. My version of Windows x64 does in fact have a `Program Files (x86)` folder, and [my research to confirm what you say](http://www.howtogeek.com/129178/why-does-64-bit-windows-need-a-separate-program-files-x86-folder/) lead to this article claiming that the `(x86)` is a fundamental part of Windows x86.

Can you confirm that you both have Windows x64 and that your `Program Files (x86)` folder does not in fact exist?

**Comment by igusse** [comment]
Hello, I have same problem. 

Windows 8 x64. I put GG to Program Files (x86)/Common Files/Adobe/CEP/extensions and got this error.  

![w250629](https://cloud.githubusercontent.com/assets/4283603/8353921/ffa1a502-1b4b-11e5-8310-42ebd01585b4.png)

**Comment by cameronmcefee** [comment]
Hi @igusse, That's actually a different problem. See this thread for more info: https://github.com/guideguide/support/issues/135

**Comment by Kallizm** [comment]
@ghost I ran into the similar misunderstanding earlier today. I assumed it was two versions of the same extension (one being x64 and one being x86). It's just an x86 version so Cameron's directions were clarifying which folder it needs to go into depending on your version of Windows. Below is a screenshot indicating what he was referencing. 

![screenshot_1](https://cloud.githubusercontent.com/assets/13060695/8504896/3fbe17d6-21a7-11e5-8c29-d4f447740098.png)

**Comment by LeftyDesigner** [comment]
@cameronmcefee I'm having the same problem with the extension not showing up in Windows PSD CC 2015. I've copied the zipped folder into both Program Files folders just to make sure and no dice (I'm on Windows 8.1).

**Comment by cameronmcefee** [comment]
Hi @LeftyDesigner,

I'm happy to help. Please open a new issue and provide a screenshot of your installed GuideGuide folder.
