### ISSUE TITLE
Not working Photoshop CC 2015 on Mac

### ISSUE THREAD

**Issue by RayKeys** [guideguide/support#156]
I installed this extension manually, and it still doesn't work. VERY FRUSTRATIING! It is not showing up in my window----> Extensions

**Comment by cameronmcefee** [comment]
Hi @RayKeys,

That is indeed frustrating! Can you confirm that your folders look like this:

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

Can you also confirm that you've installed it into the *system* library folder and not your *personal* library folder? You can run the following command in the terminal to open the correct folder:

```
open /Library/Application\ Support/Adobe/CEP/extensions/
```

**Comment by julievdb** [comment]
I had the same problem. It used to work with PS CC 2015, but suddenly it stopped working. Then I compared my folders to the screenshot here and I saw a difference. Don't move the complete unzipped folder to the extensions folder. When you open the unzipped folder, you see another folder called 'GuideGuide'. This is the one you have to move there. That's how I solved it.

**Comment by cameronmcefee** [comment]
Thanks @julievdb! I updated the name of the zip folder last night to be different, so hopefully this confusion will be avoided in the future.

**Comment by RayKeys** [comment]
Got it to work thanks

**Comment by cameronmcefee** [comment]
Glad to hear it @RayKeys!

**Comment by McGuireDesign** [comment]
can someone help me with the directory paths? 

open /Library/Application\ Support/Adobe/CEP/extensions/

this isn't clear to me is that one path or two paths? I'm not seeing this folder

**Comment by RayKeys** [comment]
Now I am having issues. It's not creating my grid when I put in values

**Comment by cameronmcefee** [comment]
@RayKeys can you clarify? Is it providing any sort of error or notable behavior?

To confirm, you're clicking the "add guides" button, correct?

**Comment by RayKeys** [comment]
There's no error. I'm hitting the make grid button after I put my calculations, but nothing appears.

**Comment by cameronmcefee** [comment]
@RayKeys Can you provide a screenshot of what you've entered into the GuideGuide form?

Can you also confirm that, after trying to add the guides, toggling the guide visibility doesn't reveal them (this was an issue with old versions of GuideGuide, where the guides wouldn't show by default despite being there).

Also, to rule out a few other potential issues, can you confirm the following:

- You have document open
- At least one layer is selected
