### ISSUE TITLE
Photoshop CC 2015 guides with multiple artboards

### ISSUE THREAD

**Issue by dwillym** [guideguide/support#157]
Unless I'm missing something, when using multiple artboards in Ps CC 2015, the controls for GuideGuide seem to apply to the whole canvas, not individual artboards. So if I have 2 same-sized artboards side by side that are each 400px wide, selecting to make a "quick midpoint guide" in GuideGuide draws a guide smack in the middle of both artboards (i.e., the middle of the canvas) rather than at the 200px point of the selected artboard.

**Comment by cameronmcefee** [comment]
Hi @dwillym,

What you're trying to do should work! A couple things to check:

Do you have the most recent version of GuideGuide (3.2.0) installed?

Do you have only one artboard selected when you run GuideGuide? If you have more than one selected in the layers palette, GuideGuide will use them both as the reference area.

**Comment by dwillym** [comment]
You are correct, I was not selecting artboards via the layers palette. My mistake. Thank you!

**Comment by cameronmcefee** [comment]
Glad to hear it's working!
