### ISSUE TITLE
Unable to install Mac Photoshop 2015

### ISSUE THREAD

**Issue by McGuireDesign** [guideguide/support#158]
I've tried putting that folder in several places, but nothing is working as I don't know the directory to place the folder... is there an install file or something?

**Comment by cameronmcefee** [comment]
Hi @McGuireDesign,

Unfortunately, no there is no install file. Adobe removed the ability to do that in CC 2015.

Assuming you're on OSX, there are two common issues I've seen with installation:

- Be sure you're installing into the *system* Library folder, not the *user* library folder. You can open the correct folder by running the following command in the Terminal:

  ```
  open /Library/Application\ Support/Adobe/CEP/extensions/
  ```

- Be sure your folders look like this:

  ![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by McGuireDesign** [comment]
putting this in terminal didn't work:

open /Library/Application\ Support/Adobe/CEP/extensions/

- - -

but I found the location myself and looks like its in there now. I'm going to test it.

**Comment by McGuireDesign** [comment]
looks like it works.

**Comment by cameronmcefee** [comment]
I'm glad to hear it's working. I'm curious why the command didn't work though. What didn't work about it?
