### ISSUE TITLE
Guide Guide still doesn't show up in photoshop CC 2015

### ISSUE THREAD

**Issue by marieyuan43** [guideguide/support#160]
Hello, Cameron

This is Marie, whose Guide guide is not showing up again in photoshop CC 2015. I tried the method you told me, which is following the instruction on the guide guide link. However, it doesn't show up now again. I tried create a CEP folder because I don't have one. somehow guide guide still doesn't show up. 

I am hoping you can help me.  Thank you.

**Comment by cameronmcefee** [comment]
Hi @marieyuan43,

Assuming you're on OSX, there are two common issues I've seen with installation:

- Be sure you're installing into the *system* Library folder, not the *user* library folder. You can open the correct folder by running the following command in the Terminal:

  ```
  open /Library/Application\ Support/Adobe/CEP/extensions/
  ```

- Be sure your folders look like this:

  ![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by marieyuan43** [comment]
Hello, Cameron

Here is how it looks like without the icon on my computer. So far. it works
again.  will wait and see how it goes.
[image: Inline image 1]

Thank you so much for the help again.

Sincerely
M

**Comment by cameronmcefee** [comment]
Hi @marieyuan43,

Unfortunately images attached to email replies don't show up on GitHub. However, I'm glad to hear it's working for you. I'm going to close this issue for now, but feel free to reopen if the issue continues.
