### ISSUE TITLE
CC2015 Bug: Automatic "Select all" and "Deselect" everytime a document is shown

### ISSUE THREAD

**Issue by kroegercommunication** [guideguide/support#163]
Since I upgraded Photoshop to CC2015 and GuideGuide to 3.2.0 this is what happens: 

– On opening a PSD, the first thing Photoshop automatically does is to select all and to deselect right after that 
– When I open a smart object out of that PSD it does the same there 
– When I switch between the PSD and the smart object or any another document (Ctrl-Tab) it does the same 
– The result is a slight delay on switching between documents and a history fully loaded with useless actions 

Have a look at the screenshot ("Protokoll" is German for "History", "Arbeitsfläche wählen" means "Select all", "Auswahl aufheben" means "Deselect"). 

![bildschirmfoto-2015-07-07-um-14 42 54](https://cloud.githubusercontent.com/assets/13219687/8566964/fb4b8c8c-2561-11e5-910d-5e14e41ff61e.png)

At first I thought it was a bug within Photoshop, but when I removed the GuideGuide extension, everything worked fine again.

Could you please fix that bug? GuideGuide is my favourite extension, and I'd love to use it again... thanks!!

**Comment by cameronmcefee** [comment]
Hi @kroegercommunication,

Thanks for the report. This an unintended side effect of the workaround that's necessary to support the new CC 2015 artboards. I'll look into this to see if there is a way to avoid it.

**Comment by cameronmcefee** [comment]
I've looked a bit into this and it will take more time to fix than I currently have available (very busy work week). However, I'd like to get a new version out as soon as I can find the time. In the mean time, you can install the previous version: http://guideguide-downloads.s3.amazonaws.com/3.1.4-guideguide-cc2015.zip

That version doesn't support artboards by default, however you can work around this by using the trick that is the cause of the bug you're experiencing, by selecting all. When you select all with an artboard selected, the selection will fill the artboard, and GuideGuide will use that selection. It'll be an OK, though not ideal, workaround until I can fix things up.

**Comment by kroegercommunication** [comment]
Thanks for the great support, Cameron! Just installed 3.1.4 and it works fine again. I'll be checking your website from time to time to see if there's an update. Cheers!

**Comment by cameronmcefee** [comment]
Hi @kroegercommunication,

I just published [3.2.1](http://guideguide.me/) which fixes this. Give it a try. Let me know if you come across any further issues. And thanks again for finding this one!

**Comment by cameronmcefee** [comment]
Someone reported that I published a version with a bad signature last night. It's been updated now, but if you downloaded it before 8:30 am PST, you'll need to download the newest version.
