### ISSUE TITLE
Installation location CC2015

### ISSUE THREAD

**Issue by rikgierman** [guideguide/support#164]
I tried pasting the files in the directory 
C:\Program Files\Common Files\Adobe\CEP\extentions\GuideGuide

But its not working
What does ''CEP'' stand for
Am i doing it wrong?

**Comment by cameronmcefee** [comment]
Hi @rikgierman,

Can you provide me a couple details so I can debug the issue?

1. Are you using Windows x32 or x64? You can find this out by doing the following:

  > 1. Click Start.
  > 2. Right-click My Computer, and then click Properties.
  >  - If you don't see "x64 Edition" listed, then you're running the 32-bit version of Windows XP.
  >  - If "x64 Edition" is listed under System, you're running the 64-bit version of Windows XP.

2. Can you provide a screenshot of the file tree so I can see whether the files were installed correctly. It needs to show at the *extensions* folder, and the contents of the *GuideGuide* folder

To answer your question about CEP, it stands for *Common Extensibility Platform*, and is the framework used to create Photoshop extensions. Depending on how curious you are, [this guide](http://www.adobe.com/devnet/creativesuite/articles/adobe-cep-apis.html) explains a bit more about it.

**Comment by scaryassghost** [comment]
Hey @cameronmcefee - I think I'm experiencing the same problem. I placed the unzipped folder into the specified location for Windows x64:
![screen01](https://cloud.githubusercontent.com/assets/13263234/8608149/1d4a6524-264d-11e5-83c1-80d5b76a849c.png)

I have another extension in there (AnimDessin) that DOES work, so this seems like the correct location.

I opened Photoshop, but did not see GuideGuide in my extensions menu:
![screen02](https://cloud.githubusercontent.com/assets/13263234/8608179/633ec002-264d-11e5-96d8-1c1d591d9049.png)

I then tried putting the extracted GuideGuide folder into a folder called "GuideGuide" to see if that made a difference, but it didn't:
![screen03](https://cloud.githubusercontent.com/assets/13263234/8608228/b695d484-264d-11e5-8b95-2b9c632dfcda.png)


Any ideas?

Thanks!

**Comment by cameronmcefee** [comment]
Hi @scaryassghost,

It's likely caused by the folder order. I can't see what's inside the GuideGuide folder, but it should look like the windows equivalent of this:

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by rikgierman** [comment]
I have the exact same mockup as both other posts show (on Windows 8.1 64 bit
No other plug-in shows after i past guideguide folder. My extensions just are empty within Photoshop after restart.
Why did Adobe had to remove

**Comment by rikgierman** [comment]
Why did Adobe had to remove The plug-in manager 😂

**Comment by cameronmcefee** [comment]
@rikgierman You mentioned you put it in `C:\Program Files\Common Files\Adobe\CEP\extentions\GuideGuide`, and that you have Windows 64bit.

The correct 64bit path is `C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\`

**Comment by scaryassghost** [comment]
@cameronmcefee Thank you, this solved my issue!

**Comment by rikgierman** [comment]
Oke thanks! It worked!

**Comment by cameronmcefee** [comment]
Great!
