### ISSUE TITLE
installing CC2015 osx 10.10.4

### ISSUE THREAD

**Issue by Holloweaver** [guideguide/support#166]
hi there,

despite placing the unzipped folder in the extension-folder (> opened with that Terminalcommando) i can't seem to activate my favourite psd-plug-in. No panel to be found and not under 'Window / Extensions'. Maybe i'm doing something stupid, i don't know, but what i do know is that you don't know what you're missing until it's gone ;) any tip is welcome...

**Comment by cameronmcefee** [comment]
Hi @Holloweaver 

- Be sure you're installing into the *system* Library folder, not the *user* library folder. You can open the correct folder by running the following command in the Terminal:

  ```
  open /Library/Application\ Support/Adobe/CEP/extensions/
  ```

- Be sure your folders look like this:

  ![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by Holloweaver** [comment]
hi, thank you for the quick response, i'll place a screenshot so that you can see the exact place where i've put the guideguide-map. 'Bibliotheek' means 'Library', it's a dutch OSX :)
![schermafbeelding 2015-07-15 om 07 50 31](https://cloud.githubusercontent.com/assets/13313137/8691750/2242f3f6-2ac7-11e5-8fcb-2680bba51f4d.png)

**Comment by Piamelissa** [comment]
Hi, i've got a little problem with the installation on photoshop CC2015 : the folder extention doesn't exist. You can see it on the screenshot. who can i do ?
![capture d ecran 2015-09-14 a 11 21 30](https://cloud.githubusercontent.com/assets/14272106/9846516/dd7c4614-5ad2-11e5-9ae0-d0bccc1de2d7.png)

**Comment by cameronmcefee** [comment]
Be sure you're installing into the *system* Library folder, not the *user* library folder, or the Applications folder. You can open the correct folder by running the following command in the Terminal:

  ```
  open /Library/Application\ Support/Adobe/CEP/extensions/
  ```

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
