### ISSUE TITLE
Not working with Art Boards on PS CC 2015

### ISSUE THREAD

**Issue by kristop** [guideguide/support#167]
Is there a way to get GuideGuide to recognize the individual art board that is active and make guides relative to it. Currently, it treats the entire area as the canvas instead of the active art board.

**Comment by cameronmcefee** [comment]
Hi @kristop,

Are you using the latest version of GuideGuide? It supports artboard. It uses a bit of a hack to do it, based on selections, but it does the trick. I have a more clean version on its way soon too.

**Comment by wijzijnwolf** [comment]
Hi there @cameronmcefee - I can't seem to get the guides to work on a specific artboard. Do i have to manually input that "hack" or something? Applying it to a selection is not working either.

**Comment by cameronmcefee** [comment]
@wijzijnwolf what version of GuideGuide are you using?

**Comment by wijzijnwolf** [comment]
Downloaded the latest one from the site yesterday.

**Comment by cameronmcefee** [comment]
Can you provide screenshots of your document, GuideGuide, and your layers palette?

**Comment by kristop** [comment]
My guide is working now with my art boards.

The only remaining problem is clearing out the guides on one art board clears out all the art boards at the same time.

Thanks for your hard work.


-Kris

**Comment by cameronmcefee** [comment]
@kristop Oh, interesting observation. I guess that is a little counter-intuitive.

**Comment by SophieAnn** [comment]
I have the same problem, how do you fix it?

**Comment by cameronmcefee** [comment]
> I have the same problem, how do you fix it?

@SophieAnn Which problem are you referring too? Would you mind [opening a new issue](https://github.com/guideguide/support/issues/new)?

**Comment by SophieAnn** [comment]
@cameronmcefee its working now after the last update
