### ISSUE TITLE
The GuideGuide extension could not be loaded

### ISSUE THREAD

**Issue by sabbz103** [guideguide/support#168]
I have tried to install GuideGuide into my CC 2015 version of Photoshop multiple times but I am still receiving the "The GuideGuide extension could not be loaded because it was not properly signed" upon launch. I have been installing it correctly but when I look at the screenshot, there are two files that are missing.

The files "META-INF" folder and the "mimetype" document are not included in the download zip on the website. Is there a way this can be updated?

**Comment by cameronmcefee** [comment]
Hi @sabbz103,

You're right! I didn't update the bundle properly. I've uploaded a new version that includes all the correct files. Please try the from http://guideguide.me/ and let me know if you have any issues with it.

**Comment by sabbz103** [comment]
It works now, thanks!!
