### ISSUE TITLE
Guide Guide extension is not working. PS says,"The GuideGuide extension could not be loaded because it was not properly signed."

### ISSUE THREAD

**Issue by RanganaC** [guideguide/support#169]

**Comment by acandael** [comment]
I'm having the same issue. I ran the command in the terminal

    open /Library/Application\ Support/Adobe/CEP/extensions/

then I copied the guideguide folder to the above folder, but when I open the guideguide extension in PS I get the message:

    The GuideGuide extension could not be loaded because it was not properly signed.

**Comment by cameronmcefee** [comment]
Apologies, I uploaded a bad bundle last night. If you [redownload/install GuideGuide](http://guideguide.me/) everything should work as expected.

**Comment by RanganaC** [comment]
Thanks alot. worked super fine.

On Fri, Jul 17, 2015 at 9:01 PM, Cameron McEfee <notifications@github.com>
wrote:

> Closed #169 <https://github.com/guideguide/support/issues/169>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guideguide/support/issues/169#event-358614712>.
>



-- 
Thanks and Kind regards,
RanganaC.
