### ISSUE TITLE
Alert "fallback to doc" is shown

### ISSUE THREAD

**Issue by jjeising** [guideguide/support#170]
When dragging a large Smart Object into a document with an Artboard GuideGuide issues the alert _fallback to doc_. There probably shouldn't be an alert. It would be also helpful to prefix the message with "GuideGuide" or similar as it's otherwise indistinguishable from Photoshops alerts and maybe attributed wrong.

**Comment by cameronmcefee** [comment]
Ah, whoops, that alert shouldn't have made it into the final launch. I'll publish a new version later today.

**Comment by cameronmcefee** [comment]
Alright, 3.2.2 is available, which removes that alert: http://guideguide.me/
