### ISSUE TITLE
GuideGuide, nothing happens

### ISSUE THREAD

**Issue by thomasvg** [guideguide/support#171]
hello, i tried to put the file in the right directory, did everything that is told in description, but i dont  see it appear in the extentions. i had to create the "CEP/extensions" myself. how can i solve this?

**Comment by cameronmcefee** [comment]
Hi @thomasvg, are you using Windows or OSX?

**Comment by mattsteinruck** [comment]
Hello.
Same thing with me. 
I'm on OSX with the latest version of Adobe CC. 
I installed the unzipped folder into the specified directory, but GuideGuide does not appear in the Windows/Extensions of Photoshop.

Suggestions?
thanks.

**Comment by cameronmcefee** [comment]
Hi @mattsteinruck 

- Be sure you're installing into the *system* Library folder, not the *user* library folder. You can open the correct folder by running the following command in the Terminal:

  ```
  open /Library/Application\ Support/Adobe/CEP/extensions/
  ```

- Be sure your folders look like this:

  ![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by mattsteinruck** [comment]
indeed.
copied/pasted the link provided in terminal.
see attached.

[image: Inline image 1]

Copied the folder into that location with Photoshop closed,
and upon re-opening, this is the view:

[image: Inline image 2]

**Comment by cameronmcefee** [comment]
Hi @mattsteinruck,

Unfortunately images in email replies don't show up on GitHub. Can you post them on GitHub directly?

**Comment by mattsteinruck** [comment]
Sure, here's what I did, and the result...
![screen shot 2015-07-28 at 2 04 33 pm](https://cloud.githubusercontent.com/assets/13541842/8947896/c0b1df78-356e-11e5-9b80-9237cdda0ed8.png)
![screen shot 2015-07-28 at 2 05 24 pm](https://cloud.githubusercontent.com/assets/13541842/8947899/c527151e-356e-11e5-9c0c-e03ec795a28f.png)

**Comment by cameronmcefee** [comment]
@mattsteinruck Thanks for the screenshot! it looks like you've got too many folders in there. It should look like *extensions > GuideGuide > guideguide stuff*. 

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by mattsteinruck** [comment]
Oooooh, I see what you did there.
Copying the folder inside the folder. Dang. Ok. Sorry and thank you!
That did the trick.

**Comment by cameronmcefee** [comment]
Glad to hear it's working!
