### ISSUE TITLE
Downloaded GuideGuide file for Photoshop CC2014 is a .zxp file. 

### ISSUE THREAD

**Issue by neilpetrunia** [guideguide/support#173]
When I try dowloading the Photoshop CC2014 extension for GuideGuide, the file that downloads is 3.2.2-guideguide.zxp. My Mac knows nothing of that suffix. Why is it not downloading as a zip file?

**Comment by cameronmcefee** [comment]
Hi @neilpetrunia,

.zxp is the file format for Adobe's Extension Manager, which is the application that installs and keeps track of plugins. If you're using CC2014, you may need to download the Extension Manager, if you don't already have it. 

![monosnap 2015-07-28 14-24-10](https://cloud.githubusercontent.com/assets/72919/8944246/55d8dcfe-3534-11e5-86b0-fc699a8c0204.jpg)
