### ISSUE TITLE
ps cc 2015 gg 3.2.2 not working with selection

### ISSUE THREAD

**Issue by elspiritu** [guideguide/support#174]
win 10 x64 pro
Windows 64: C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\
Windows 32: C:\Program Files\Common Files\Adobe\CEP\extensions\

**Comment by cameronmcefee** [comment]
Hi @elspiritu,

Can you elaborate further about what "not working" means? I presume GuideGuide itself functions normally when you aren't using a selection, correct? What sort of behavior happens, or doesn't happen, when you use a selection?

**Comment by elspiritu** [comment]
when i using selection and press "make grid", dnothing happens
gg 3.1.4 is working this way

**Comment by cameronmcefee** [comment]
@elspiritu ok, here are some next steps to help me figure out what's happening:

1. Open a new document

1. Run GuideGuide with a selection and confirm that it has failed as expected

1. Take screenshots of the following:

  - the document that failed
  - GuideGuide
  - the layers palette
  - and the history palette

1. Please post those screenshots here

---

Additionally, can you confirm that it does work *without* a selection?

**Comment by elspiritu** [comment]
I hope it will be useful
![untitled-2](https://cloud.githubusercontent.com/assets/9986836/9032967/1f961868-39cc-11e5-961f-292eed7fc1c8.jpg)

**Comment by cameronmcefee** [comment]
Ok, this is helpful. From your screenshot, it appears that GuideGuide did, in fact, run successfully, as shown by the *GuideGuide!* in the history palette. I also ran the same grid you are using which worked fine.

However, I did discover a bug, wherein the artboard coordinate offset is applied to the selection, thus if you were to have, the right most artboard active with the selection is in the left most artboard, the guides would be placed incorrectly within the right most artboard.

I'm not sure if this is related to your issue, but you could test this for me:

- When you run GuideGuide with a selection, does photoshop lock up for a few seconds? If so, this would indicate it *is* adding guides somewhere.

- Can try selecting the artboard that your selection is in (if it isn't) and see if that "fixes" things?

- Can you zoom all the way out and run GuideGuide in the selection to see if the guides appear somewhere way outside the document, or in another artboard?

**Comment by cameronmcefee** [comment]
Ok, @elspiritu, I published 3.2.3 which fixes the issue I mentioned above. Download the latest from http://guideguide.me/, install it, and let me know if the problem you are experiencing still exists.

**Comment by elspiritu** [comment]
it's great, everything is working, thank you

**Comment by cameronmcefee** [comment]
Arwesome, sorry for the trouble! Thanks for your help!
