### ISSUE TITLE
What License to you offer GuideGuide under?

### ISSUE THREAD

**Issue by mjcorn** [guideguide/support#175]
I am interested in the licensing because my corporate masters require it. Also, I think you should have a buy option in addition to donate for corporate entities to use it for commercial purposes. It makes lawyers more comfortable.

**Comment by cameronmcefee** [comment]
Thanks for the suggestion @mjcorn, I'll give that consideration.

Currently, the GuideGuide codebase is licensed under the MIT license, and is thus free to use by anyone.

**Comment by cameronmcefee** [comment]
If you need to be able to provide proof of this: https://github.com/guideguide/core/blob/master/LICENSE

**Comment by mjcorn** [comment]
That is fantastic, thanks very much!
