### ISSUE TITLE
Instructions for Installing on PS CC 2015 with Windows 10?

### ISSUE THREAD

**Issue by amyfrenchink** [guideguide/support#177]
I just installed Windows 10, and I want to install guideguide. What would those instructions be? Thanks!

**Comment by cameronmcefee** [comment]
Hi @amyfrenchink,

When you select the [cc 2015 version of GuideGuide](http://guideguide.me/), the installation instructions appear below, which includes windows.

**Comment by amyfrenchink** [comment]
I think I followed those instructions, and here is a screen capture of where I put guideguide. But it is not present when I open Photoshop CC 2015. Can you see anything I've done wrong?
![image](https://cloud.githubusercontent.com/assets/13632523/9061928/9cd67bf2-3a84-11e5-8380-927d92218834.png)

**Comment by cameronmcefee** [comment]
@amyfrenchink You will need to move that file somewhere else (your desktop, perhaps), unzip it, and copy the resulting *GuideGuide* folder into the directory you have open now.

**Comment by amyfrenchink** [comment]
I moved the zip file, and put back only the GuideGuide file, as you suggested. But GuideGuide still isn't appearing when I open Photoshop. I look in Window < Extensions, but there I see only Adobe Color Themes.

Here is a photo of the unzipped file in its current location. 
![image](https://cloud.githubusercontent.com/assets/13632523/9065252/2b64c1f6-3a96-11e5-901e-0579bc08e3d1.png)

**Comment by cameronmcefee** [comment]
Oh, looks like your path isn't right (had to look again). The correct path is C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\

**Comment by amyfrenchink** [comment]
Hooray! That worked like a charm. Thank you!

**Comment by cameronmcefee** [comment]
:metal: Glad to hear it. Happy guiding!
