### ISSUE TITLE
After Update Adobe photoshop CC 14 guideguide is working.

### ISSUE THREAD

**Issue by alamm5421** [guideguide/support#178]
![image](https://cloud.githubusercontent.com/assets/13703376/9157395/872fe3cc-3f1d-11e5-959d-c9e64bc9df2d.png)

After Update Adobe photoshop CC 14 guideguide is working. for update help <b>menu to updates..</b>

![image](https://cloud.githubusercontent.com/assets/13703376/9157403/def520cc-3f1d-11e5-9d64-08bdaadce2f8.png)

**Comment by cameronmcefee** [comment]
@alamm5421 Is something not working?
