### ISSUE TITLE
GuideGuide opens with no UI for a second then closes

### ISSUE THREAD

**Issue by trend2** [guideguide/support#179]
I have used GuideGuide on CS6 with no problems. It has been a fantastic tool with which I have been able to create type layouts with more ease and precision than at any point in history.

I have just installed CC and tried to install GuideGuide, however it opens for a second with no UI before closing. I have reinstalled GuideGuide, tried different versions, tried the direct install, tried everything and it is incredibly frustrating. I am using Windows 7 64 with Photoshop CC installed alongside CS6.

I hope a solution is found soon because I have learned to take GuideGuide for granted and only now am I realising what a leap forward this tool provides for Photoshop. 

Thanks.

**Comment by cameronmcefee** [comment]
This sounds like it might be related to [this thread](https://github.com/guideguide/support/issues/176), though there unfortunately isn't a resolution yet.

What happens if you run Photoshop as Administrator?

> 1. Locate the program icon or a shortcut in Windows Explorer.

> 2. Right-click the program icon or shortcut, and then click Run as administrator.

**Comment by trend2** [comment]
Hi,

Thanks for the response. I ran it as an admin however the same issue occurred.
I may try to reinstall Photoshop, as I have noticed problems when working with vector shapes, when a point is selected a dialogue appears stating [img]http://puu.sh/jyV4M.png[/img]

**Comment by cameronmcefee** [comment]
Ah yeah, this feels like one of those "something is messing everything up" kind of things.

**Comment by trend2** [comment]
I think it had something to do with having both CS6 and CC installed simultaneously. I reinstalled Windows on a new disk and with a fresh install of Photoshop have GuideGuide running perfectly.

**Comment by cameronmcefee** [comment]
@trend2 I'm glad to hear you were able to get it working!
