### ISSUE TITLE
Please help. cannot install guideguide into extension manager cc

### ISSUE THREAD

**Issue by Kornerpocketkid** [guideguide/support#180]
Hi, im running on osx and have downloaded the guideguide file for photoshop cc 2015 and i cannot  find the "extensions" folder to copy the guideguide folder into. 
these are the instructions on guideguide.me:
 Launch Terminal and run this command to open the install folder (or open the folder yourself):
open /Library/Application\ Support/Adobe/CEP/extensions/
Copy the unzipped GuideGuide folder into the extensions folder. It should look like this.

perhaps is there more detailed instructions than the ones offered on the site? thanks in advance!

**Comment by cameronmcefee** [comment]
Hi @Kornerpocketkid,

What happened after you ran the suggested terminal command?

**Comment by Kornerpocketkid** [comment]
oops. didnt realize that after i typed in the terminal command the window that popped up was actually the  "extensions folder" that i was looking for. sorry, new to osx. thanks anyways!

**Comment by cameronmcefee** [comment]
@Kornerpocketkid all good, welcome to the OSX club! So is it working now?
