### ISSUE TITLE
GG 3.2.3 :: CC 2014 :: Can not be installed

### ISSUE THREAD

**Issue by yozhic** [guideguide/support#181]
I have Photoshop CC 2014.2.2 (20141204.r.310 x64) and Extension Manager CC 7.0.0.347 on MacOSX. So, my attempt to install the extension for CC 2014 finishes with the message “This extension can not be installed, it requires Photoshop version 12 or greater.”
![screencapture2015-08-22_04-17-55_pm](https://cloud.githubusercontent.com/assets/13917732/9424128/44a76aae-48e9-11e5-970f-aaa2590049a6.jpg)
Can this be fixed?

**Comment by cameronmcefee** [comment]
Hi @yozhic,

The latest version of the Extension Manager is 7.3.2.39. Updating will most likely fix the issue for you.

**Comment by yozhic** [comment]
Thanks, now everything is fine. These applications have many expectanions.

**Comment by cameronmcefee** [comment]
Great, I'm glad to hear it's working!
