### ISSUE TITLE
Instant Crash in Photoshop CS6 13.0.6 Mac OS 10.10.4

### ISSUE THREAD

**Issue by dbat777** [guideguide/support#185]
I've been using guide guide for a while on CS6 but recently after moving to a new machine with a brand new install of CS6 version 13.0.6 I'm getting an instant crash when trying to open the extension window. The wind appears as white and then flashes and then Photoshop just crashes. As long as I keep Guide guide off photoshop will stay stable. I recently tried deleting the extension through extension manager and re-downloading and re-installing but still no luck. 

Does anyone have any ideas how to fix or if its a bug? I really love this plugin and am super bummed not being able to use it anymore. 

Thanks!

**Comment by cameronmcefee** [comment]
Hi @dbat777,

This is unfortunately one of those things that—to the extent I've been able to investigate—is a Photoshop-dependent problem. In some cases, people have had luck fixing it by reinstalling Photoshop itself. My hunch is that it's some sort of system/Photoshop settings issue that the reinstall resets.

**Comment by dbat777** [comment]
Hi @cameronmcefee,

Thanks for the quick response. We tried reinstalling the entire CS6 suite and still see the issue. Stable until loading the extension and then instant crash.  Any other ideas?

**Comment by cameronmcefee** [comment]
Ugh, sorry to send you on a wild goose chase. I have no perfect answer, but here are a couple things:

- The version of CS6 I have is 13.1.2. You can try updating your version.

- Uninstall GuideGuide with the Extension Manager

  Open Terminal and run this script:

  ```
  open ~/Library/Application\ Support/Adobe/CS6ServiceManager/extensions/ && open /Library/Application\ Support/Adobe/CS6ServiceManager/extensions/
  ```
  
  It will open two finder windows to the two places Adobe installs extensions. If you see any GuideGuide folders, delete them.

  Reinstall GuideGuide

**Comment by dbat777** [comment]
Hi again, thanks for the response. 

Unfortunately version 13.1.2 seems only available from the CC version.
http://www.adobe.com/support/downloads/product.jsp?product=39&platform=Macintosh
We only have the original CS6. :( Will the plugin not work on the CS6 version 13.0.6?

**Comment by cameronmcefee** [comment]
Hi @dbat777 

That's odd, here's what mine looks like:

![screen shot 2015-09-21 at 12 32 46 pm](https://cloud.githubusercontent.com/assets/72919/10002583/e20841ee-605c-11e5-9c5b-5ad6482cd611.png)

> Will the plugin not work on the CS6 version 13.0.6?

It certainly should. Instant-crash issues are usually Photoshop/system related, where GuideGuide triggers an inherent flaw in the system, rather than GuideGuide being the actual cause of the problem. The best solution people have had luck with so far is to reinstall Photoshop, as that starts them over with a blank system-settings slate.

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
