### ISSUE TITLE
cant install guide guide in Photoshop CC 2015

### ISSUE THREAD

**Issue by katdeleon** [guideguide/support#187]
I upgraded my adobe extension manager but guide guide still it isn't showing up the under extensions tab in the photoshop. I'm running OS 10.10.5.

**Comment by cameronmcefee** [comment]
Hi @katdeleon,

Unfortunately Adobe removed support the Extension Manager in CC 2015, so a manual install is required. Be sure to download the CC 2015 version of GuideGuide from http://guideguide.me/ and follow the manual install instructions. If it's still not appearing after manual install, please let me know.

**Comment by katdeleon** [comment]
Thanks, I wasn¹t taking the GuideGuide folder out of the
3.2.3-guideguide-cc2015 folders. Your illustration of "it should look like
this" was the key.

Kat DeLeon
(917) 301-7965
kd@katdeleonphoto.com
Please visit my website at:
           www.katdeleonphoto.com


From:  Cameron McEfee <notifications@github.com>
Reply-To:  guideguide/support
<reply+00e22b5d4b34a7b35dc4a9a0b85a834ca44aa78769fc1f6c92cf00000001121bd7099
2a169ce0671fb3b@reply.github.com>
Date:  Thu, 24 Sep 2015 08:21:45 -0700
To:  guideguide/support <support@noreply.github.com>
Cc:  Kat DeLeon <kd@katdeleonphoto.com>
Subject:  Re: [support] cant install guide guide in Photoshop CC 2015 (#187)

**Comment by cameronmcefee** [comment]
I'm glad to hear it. Happy guiding!
