### ISSUE TITLE
Install not working in CC2015

### ISSUE THREAD

**Issue by crisaphi** [guideguide/support#188]
I used the terminal address to do the install and placed the unzipped folder in there. Restarted PSD and still nothing shows. Thoughts? 
<img width="2411" alt="screen shot 2015-09-25 at 1 56 16 pm" src="https://cloud.githubusercontent.com/assets/14842596/10110873/3c159596-638d-11e5-8c41-1aaccc2571c4.png">

**Comment by cameronmcefee** [comment]
Hi @crisaphi 

Sorry for the trouble! If you look inside that `3.2.3-guideguide-cc2015`, there's a folder called `GuideGuide`. If you move that folder into the `extensions` folder, it should work as expected (you can delete the `3.2.3-guideguide-cc2015` once you've done this.

When you're done, it should look like this:

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by crisaphi** [comment]
Agh thank you. Yes, that fixed my issue. Thanks!



Crissie McDowell  |  art director  |  208.287.6538  |  oliverrussell.com<http://oliverrussell.com/>
[line]
[Oliver Russell]<http://oliverrussell.com/>     We build brands for purpose-driven companies    [http://www.oliverrussell.com/stuff/contentmgr/files/0/dcbe594de016b1433e88a5c8f7f101a4/files/b_corp.gif]

**Comment by cameronmcefee** [comment]
Glad to hear it!
