### ISSUE TITLE
4.0.0: Interface modification suggestions

### ISSUE THREAD

**Issue by BevansDesign** [guideguide/support#189]
The new v4 interface seems a lot better than it was previously (tabbing and selecting text work much better), but I have a couple issues:

1. I'd like the option to always show the bottom row of buttons. (Top/Left/Middle borders, clear guides, etc.) Those are pretty useful to me, and I hate auto-hiding toolbars. 

2. Can you put the Add Guides, Save Grid, and Reset Form buttons on a single line again? Right now they take up way more vertical space in my toolbar panel than they used to.

**Comment by cameronmcefee** [comment]
Thanks for the feedback, @BevansDesign!

> 1. I'd like the option to always show the bottom row of buttons. (Top/Left/Middle borders, clear guides, etc.) Those are pretty useful to me, and I hate auto-hiding toolbars.

This is a common request. I chose to do this to save room for the form, but I'm definitely taking your feedback and feedback from others into account for future versions.

> Can you put the Add Guides, Save Grid, and Reset Form buttons on a single line again? Right now they take up way more vertical space in my toolbar panel than they used to.

Do you find you use Save Grid and Reset Form often? They are hidden away because they are not commonly used actions.

**Comment by benishs** [comment]
+1 on always showing the bottom row of buttons – I use the midpoint buttons *a lot*. The hit area to reveal that toolbar is easy to overshoot.

**Comment by cameronmcefee** [comment]
@benishs The latest version has the buttons always shown. Be sure to update to the latest!

**Comment by benishs** [comment]
@cameronmcefee Thank you!

**Comment by BevansDesign** [comment]
>Do you find you use Save Grid and Reset Form often? They are hidden away because they are not commonly used actions.

I don't use Save Grid very often, but I do use Reset Form pretty often.

One more thing I just thought of: when you use Tab to switch through the number fields, could you make it so it selects all the text that's already in the field, so I can type without having to manually select the text? I know an older version of GG had this feature, but it got lost somewhere along the way.

**Comment by cameronmcefee** [comment]
Thanks for the suggestion @BevansDesign. I seem to recall I was not able to reproduce the selection behavior to my liking with now Adobe panels work now, but that seems silly. I'll take another look at it.
