### ISSUE TITLE
Cannot install via extension

### ISSUE THREAD

**Issue by VuPixels** [guideguide/support#190]
I have Photoshop CC (2015) and tried to install the via Adobe extension the GG PS 2015 version. 
I get an error message:
(https://cloud.githubusercontent.com/assets/2109810/10581839/b0b0a8b4-7652-11e5-89bd-9e96cdbe8d51.png)

**Comment by cameronmcefee** [comment]
Hi @VuPixels,

Adobe dropped support for the Extension Manager in CC 2015. You can find installation instructions for CC 2015 here: http://guideguide.me/documentation/installation/

**Comment by romuloinnocencio** [comment]
Thanks, this last link in Windows works fine! =)
