### ISSUE TITLE
Guides only work on first Artboard

### ISSUE THREAD

**Issue by TwanBB** [guideguide/support#192]
This issue was recently closed, updating to 4.1.1 does not seem to solve the problem. When i try to add a new grid it keeps being added to my first artboard instead of the one i currently have selected.

**Comment by cameronmcefee** [comment]
Hi @TwanBB are you able to provide a screen recording? I am not able to reproduce the issue.

**Comment by TwanBB** [comment]
I have recorded a screencast of the problem, you can find it on url: https://vimeo.com/148062789
The password is guideguide

**Comment by cameronmcefee** [comment]
Hi @TwanBB,

Thank you for the screencast. That behavior is strange. Can you provide the following:

- What version number is Photoshop?
- Have you tried 4.1.2 which I released after your original message?
- Are you willing to share the file with me so I can try it directly? You can send it to guideguide@cameronmcefee.com

**Comment by cameronmcefee** [comment]
Thanks again for the report @TwanBB. I just published 4.1.3 which includes the fix. If you purchased GuideGuide, you should have an email with a link to your download. If you're using the trial, you can grab the latest download from guideguide.me
