### ISSUE TITLE
Lots of different issues I am noticing

### ISSUE THREAD

**Issue by haydenhancock** [guideguide/support#193]
First, I am using Windows 10 x64 Enterprise and Adobe Photoshop 2015 CC (20151114.r.301x64).

I am having a lot of issues with this extension for the brief time that I've used it (first 5 minutes). I have an existing document for which has multiple artboards on it. I've selected the artboard so the context should be the selected artboard, however, when selecting the "Center" option, it appears the grid context has changed to the document. If I use the "Left" or "Right" it seems to work as expected. 

I also tried creating a new document with two blank artboards at 1440x900 and created a 1170 grid with grid notation of:

`$v = | 70px | 30px |
$vC = | 70px |
| $v*11 | $vC | ( vlp, ~ | ~ )`

It seems to work great on the first arboard, but any subsequent artboards it messes up. When I select the second artboard and click "Add Guides" it creates it on the first artboard.

Suggestions of screen capturing software so I can take a video?

**Comment by cameronmcefee** [comment]
Hi @haydenhancock,

Both scenarios you mention are related to the same issue. I'm working on a fix as we speak for it. The only workaround for things is to use the "left" orientation or in the grid notation change the options at the end to `(vlp, | ~)` which will left align the grid. Sorry for the trouble, I hope to have the fix out soon.

**Comment by cameronmcefee** [comment]
If you're curious, the reason is that In CC 2015.1, the new artboard guides are added relative to the artboard but are tracked relative to the document. GuideGuide has to do some math to accommodated for all the offset positions and in my haste to roll out support I missed a couple edge cases

**Comment by haydenhancock** [comment]
Thanks for the quick response.  I've been using your plugin for quite some time (pre CC) and I truly appreciate the amount of time spent developing it. It's quite useful.

**Comment by haydenhancock** [comment]
@cameronmcefee I am able to get around the bug by adding the proper margin to the left and right, in my case 135px. My grid notation is now

`$v = | 70px | 30px |
$vC = | 70px |
| 135px | $v*11 | $vC | 135px | ( vlp, | ~ )`

Looking forward to the fix for "Center" grids though! Any ETA?

**Comment by cameronmcefee** [comment]
I just published 4.1.3 which includes the fix. If you purchased GuideGuide, you should have an email with a link to your download. If you're using the trial, you can grab the latest download from [guideguide.me](http://guideguide.me)

**Comment by haydenhancock** [comment]
@cameronmcefee Awesome. Seems to work great!
