### ISSUE TITLE
No CEP/extensions folder on Adobe Photoshop CS5 ME

### ISSUE THREAD

**Issue by MehdiDehghani** [guideguide/support#194]
Hi,

I have installed Adobe Photoshop CS5 ME and found out there is no CEP folder, so how I can use extentons?

**Comment by cameronmcefee** [comment]
Hi @MehdiDehghani,

To clarify, the latest version of GuideGuide only supports CC+, however if you're using one of the older versions of GuideGuide, the folder is called `CS5ServiceManager`.
