### ISSUE TITLE
Artboard Alignment

### ISSUE THREAD

**Issue by mikelinsey** [guideguide/support#196]
When I make a grid, it appears offset by 831px from the left margin. Was working fine previously, and have restarted photoshop to no avail. This happens on all artboards on the page, regardless of the individual grid settings.

![gg-offset](https://cloud.githubusercontent.com/assets/16349831/11895941/6822146e-a57a-11e5-931d-17554a5c756d.JPG)

**Comment by cameronmcefee** [comment]
Hi @mikelinsey,

While it may work in some circumstances, GuideGuide 3 is no longer supported now that GuideGuide 4 is available, which works with Adobe's new artboard system. You can find more info about it here: http://guideguide.me/
