### ISSUE TITLE
Extension not properly signed

### ISSUE THREAD

**Issue by zmetak** [guideguide/support#198]
I have purchased the GuideGuide for me and 2 other designers today.
It works on my computer, doesn't work on theirs.
Here are contents of the folders:
![screen shot 2016-01-14 at 3 10 33 pm](https://cloud.githubusercontent.com/assets/1193363/12340786/eed8e50c-bad1-11e5-9597-ac0599f4540c.png)
![screen shot 2016-01-14 at 3 12 55 pm](https://cloud.githubusercontent.com/assets/1193363/12340787/eed916da-bad1-11e5-8065-9d63b6c01aaf.png)

We have tried all the suggestions we could find, but none of them worked. Any help is appreciated. Thank you!

**Comment by cameronmcefee** [comment]
Hi @zmetak,

Sorry for the trouble! Assuming your versions of Photoshop are up to date (early CC versions had a bug that caused that error) that error happens when one of the files in the GuideGuide folder gets modified. It's possible that during the installation something accidentally got changed. I've seen that happen when it is put into a Dropbox folder (which rewrites the files) or a non-native zip utility is used. The only way to fix the issue is to delete the GuideGuide files and install again.

**Comment by zmetak** [comment]
All of our PS versions are up-to-date (2015.1.1). I've shared that file through Dropbox so perhaps that might have caused it. 

What are the suggested steps to delete the installation of GuideGuide files? I've searched the folder structure and there are several locations where GuideGuide files are deployed. We used to have previous versions of GuideGuide on all of these computers. Also running the uninstall file did not really remove all of the GuideGuide files.

Anyway I will redownload the zip package directly and try to install it like that on affected computers and let you know on Monday (PST).

**Comment by cameronmcefee** [comment]
> I've shared that file through Dropbox so perhaps that might have caused it.

For the sake of experiment, would you mind running this command in Terminal.app on the machine that works and one of the ones that don't?

I'm guessing it's probably safe to store the zip file on dropbox. My suspicion is that if you put it in Dropbox as extracted files, Dropbox rewrites the files somehow when it syncs, which invalidates the signature.

```
find /Library/Application\ Support/Adobe/CEP/extensions/GuideGuide -ls
```

It'll print out a list of all the files, their locations, and the time of last modification. I'm hoping to compare the lists to the published installer to see where things changed.

> What are the suggested steps to delete the installation of GuideGuide files?

You can use this guide to find your installation folder: http://guideguide.me/documentation/installation-folder/ Deleting that folder will delete GuideGuide. You can restart Photoshop to confirm it's gone.

The open source installer I'm currently using seems to "install" a few empty folders around your Adobe files, which have no effect on anything, so you can ignore or remove them. It's something I'm looking to remove in future versions. Here are their locations on OSX, if you want to remove them:

```
/Applications/Adobe\ Photoshop\ CC\ 2015/Plug-ins/GuideGuide/
/Applications/Adobe\ Photoshop\ CC\ 2015/Presets/Scripts/GuideGuide/
```

> Also running the uninstall file did not really remove all of the GuideGuide files.

Good to know. I'll look into fixing that in the open source project.

**Comment by zmetak** [comment]
> For the sake of experiment, would you mind running this command in Terminal.app on the machine that works and one of the ones that don't?

[guideguide-not-working.txt](https://github.com/guideguide/support/files/94962/guideguide-not-working.txt)
[guideguide-working-fine.txt](https://github.com/guideguide/support/files/94963/guideguide-working-fine.txt)

**Comment by cameronmcefee** [comment]
Ah, I found the problem. It looks like the new GuideGuide was installed over the top of the old one. This, along with a few other reports I've had, lead me to believe that the open source installer I'm using doesn't remove old versions first.

If you open Terminal.app and run:

```
rm -rf /Library/Application\ Support/Adobe/CEP/extensions/GuideGuide
```

That will delete the GuideGuide folder. Then reinstall GuideGuide according to the instructions and it should hopefully work.

I'll see about updating the installer.

**Comment by zmetak** [comment]
Hey @cameronmcefee, this actually helped! Removing the old GuideGuide manually worked. Thank you for all your work and effort you've put into this and into GuideGuide. Keep it up and if you ever stop by in Vancouver, let me get you a beer or two!
