### ISSUE TITLE
Photoshop 2015.5 (v17) support

### ISSUE THREAD

**Issue by tzekin** [guideguide/support#200]
The current installation doesn't support the latest version. And even if you manually install the panel is not shown. Changing the config file and then installing via the script also doesn't seem to have any effect and the panel is not visible.

**Comment by cameronmcefee** [comment]
Hi @tzekin,

Sorry for the trouble. I've published 4.3.5 to Gumroad and Creative market which fixes the issue. If you're using the Adobe Add-ons version, Adobe lags 2-3 weeks behind. If you don't want to wait, send proof of your purchase to support@guideguide.me and I'll send you a code for a free copy through my own store.
