### ISSUE TITLE
Show a Blank page in Photoshop cc

### ISSUE THREAD

**Issue by mehedi-sharif** [guideguide/support#49]
Hi,
I have used guideguide in my photoshop cs6 version and that works awesome but while I update my version and now it shows a blank page, it means it does not show any option.How can i do now.I have already uninstall it twice but still now it does not work.
Thanks 
Mehedi

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
