### ISSUE TITLE
Guide Guide makes my Photoshop freeze

### ISSUE THREAD

**Issue by Johnny-Quid** [guideguide/support#53]
Hey guys, I have a bit of a problem here, 

I've recently noticed that when I try to make a grid on guide guide, Photoshop ( CC 64bits) freezes and I have to kill the process.

I tried to reinstall the plugin, I made an update of extension manager AND photoshop, still got a freeze everytime..

Any idea ?

Cheers

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
