### ISSUE TITLE
Not Working on Photoshop CC 

### ISSUE THREAD

**Issue by jokface** [guideguide/support#58]
![guide](https://cloud.githubusercontent.com/assets/8262703/3696904/617c9b26-1399-11e4-9afb-e0b7e30f5cf2.JPG)
I got this window when opening GuideGuide, it seems like it's not working for me
Any help please
Thank you

**Comment by alamm5421** [comment]
After update photoshop CC 14,it's working

**Comment by alamm5421** [comment]
After Update Adobe photoshop CC 14 guideguide is working. for update <b> help menu to updates..</b>

![image](https://cloud.githubusercontent.com/assets/13703376/9157422/4d33c76e-3f1e-11e5-8772-dedcbc026c8e.png)
