### ISSUE TITLE
Points are calculated as pixels

### ISSUE THREAD

**Issue by patrickplaggenborg** [guideguide/support#72]
When using the default 72dpi points and pixels are the same.
So using points in GuideGuide works just fine.

When using 144dpi (when designing retina screens in full size for example) a point (pt) becomes 2 pixels (px).

(A workaround for now is to define retina grids in double a pixel size. Would be nice to use pt's so you can use the same grid presets for both 72dpi 144dpi or any other resolution.)

It looks like GuideGuide always calculates 1pt = 1px and is not resolution dependant?

**Comment by cameronmcefee** [comment]
Thanks again for the report. I updated this in the latest version. Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
