### ISSUE TITLE
Can't save a new set

### ISSUE THREAD

**Issue by websam** [guideguide/support#73]
Hi there,

When I try to save a new set it not there when I come back to the guideguide tab.

Am I missing something here?

Best regards
Martin

**Comment by Founts** [comment]
I'm running 14.1.2 x64 and also cannot save. For now, I copy the guide script to a clipboard...

**Comment by cameronmcefee** [comment]
Wow sorry @jlillyreed, I let this one slip by me. Thanks for the bump @Founts.

So I know what is wrong as far as the flash to white and reset, however I'm unclear as to why it's doing that. Under normal circumstances that shouldn't be something that happens.

The latest version of Photoshop is version 14.2.1. Can you both make sure you're on that version? I'd also suggest uninstalling and reinstalling GuideGuide via the Extension Manager. I'm hoping a combination of those two things will sort out the issue. If not, let me know.

**Comment by Founts** [comment]
@cameronmcefee thanks for the quick response!

I'm using FontShop for testing out fonts which FontShop says doesn't work with the latest version of PS - so I have to stay with where I'm at unfortunately.  :( If you have any alternatives to FontShop, please suggest and I would gladly ditch it.

Tried removing and installing latest version and still cannot save sets.

**Comment by cameronmcefee** [comment]
@Founts just to clarify, 14.1.2 is Photoshop CC, not Photoshop CC 2014, correct? My assumption would be that FontShop's conflict is with CC 2014 and not the latest version of Photoshop CC. If that's the case, you should be able to update Photoshop CC to *its* latest version (14.2.1) without any issue.

**Comment by Founts** [comment]
@cameronmcefee That was correct, 14.1.2 is Photoshop CC. I updated to the latest version of CC (14.2.1) and GuideGuide allows me to save sets! Very much appreciate your help and GuideGuide. cc @jlillyreed

**Comment by cameronmcefee** [comment]
Glad to hear that was the case. The tech GuideGuide 3 is built on was slowly introduced over the life of CC so early versions didn't have the stuff necessary for saving sets.
