### ISSUE TITLE
GuideGuide Photoshop CC 2014 Crash

### ISSUE THREAD

**Issue by bobmosh** [guideguide/support#75]
Hi,

I just Installed GuideGuide and I want to use it sooo badly, but I'm having an issue, that makes my Photoshop crash.

The crash does not happen if there is no document open. It initializes correctly (as far as i can tell), but as soon as I open any given document, Photoshop crashes.

Adobe Photoshop Version: 2014.2.0 20140926.r.236 2014/09/26:23:59:59  x64

Hope you can help me, if you need any information, just ask!

Greetings, bob_mosh!

**Comment by Dragoy** [comment]
Hi, I have a similar problem. I have done the above points, there is no result. 
Error log (for Windows Logs): http://pastebin.com/M7Dy8B7X
Video (Crash photoshop): http://take.ms/qdwte


p.s: Sorry for my bad English language.

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
