### ISSUE TITLE
Cannot complete command because the extension could not be loaded.

### ISSUE THREAD

**Issue by keefmonkey** [guideguide/support#81]
Hello,

I've installed GuideGuide 3.1.2 via Adobe Extension Manager CC, and have it enabled. However in Photoshop CC I have the error pop up "Cannot complete command because the extension could not be loaded."

After clicking OK the GuideGuide panel is visible but blank.

Would you be able to talk me through a fix for this?

![screen shot 2014-10-16 at 10 53 27](https://cloud.githubusercontent.com/assets/9265571/4660641/5b66d392-551a-11e4-95c8-b9f8feac9aad.png)

I'm using an iMac.

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
