### ISSUE TITLE
My GuideGuide don't reconize units.

### ISSUE THREAD

**Issue by Romanjr** [guideguide/support#88]
When a fill 2cm guide, for example, he don't make the guide on 2 cm on document. 
do you know why? I work in a macbook retina, in photoshop cc2014.

thanks

**Comment by Romanjr** [comment]
Ow Sorry,

was a version problem.

i don't had the latest version

Thanks!

2014-11-07 1:23 GMT-02:00 Cameron McEfee <notifications@github.com>:

**Comment by cameronmcefee** [comment]
Np, glad to hear it's working!
