### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by igor74** [guideguide/support#91]
Hi.
I tried to install guideguide to my CC2014. But under installation the guide just finding CS6 and not CC2014 which I am using now. Should I remove my CS6 from my iMac or any other ideas?

Thanks.

:)

**Comment by zvrt** [comment]
Hi,

I had the same issue after migrating my Photoshop from CC to CC2014. Using a Win7 box on a corp network.
Problem solved, but it took long and was a bumpy ride:

1. My installed Extension Manager was CS6 and could not install GuideGuide. Deleted EM only to have an error when trying to install Extension Manager CC (described in this thread: https://forums.adobe.com/thread/1235641)
2. Delete an installed copy of Extension Manager CC
3. Log off from corporate network, log on as a local admin
4. Download Extension Manager CC from Adobe - Exchange : Download the Adobe Extension Manager
5. Install it
6. Kill the Creative Cloud core sync process with task manager (no idea how you kill a process on a mac box)
7. Go to C:\ProgramData\Adobe\Extension Manager CC\Configuration\DB and delete or rename the ExMan.db file (I guess you have to look for this file on Mac)
8. Launch Extension Manager and install GuideGuide.

BRgds

Piotr

**Comment by cameronmcefee** [comment]
Thanks for the detailed guide @zvrt! I should mention that deleting the ExMan.db file is a destructive action and should be avoided if other solutions are possible. Specifically, deleting it unlinks any installed extension from the Extension Manager which will prevent them from checking for updates by their authors (if they do so via the Extension Manager).
