### ISSUE TITLE
Export Open in Browser does not work

### ISSUE THREAD

**Issue by CptnC** [guideguide/support#95]
After I have exported my grids to the gist i can't get to the gist in my browser. When I press the button "Open in Browser" nothing happens.

I have the problem since the feature exists. Im Running Photoshop CC 2014 on a Mac Pro (Mid¬2010), 
2 x 2,4 GHz Quad-Core Intel Xeon, 12 GB 1066 MHz DDR3 ECC

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.
