### ISSUE TITLE
crash PS 2014 cc

### ISSUE THREAD

**Issue by Leighd7** [guideguide/support#99]
open panel ok

click to add guide.

photoshop error stop wroking

**Comment by cameronmcefee** [comment]
Hi @Leighd7,

Do you have a screenshot of the error?

**Comment by lance1572** [comment]
I'm experiencing the same issue. I just updated PS to the very latest release of CC 2014. I don't get a crash but a freeze and no error indication.

Here is my screenshot. 
![screen shot 2015-04-08 at 12 35 42 pm](https://cloud.githubusercontent.com/assets/7738532/7050021/2a40ab02-ddec-11e4-8992-523122c0d48c.png)

**Comment by cameronmcefee** [comment]
Hi @lance1572,

I think you're case is different. I think what's happening for you is that by specifying all those zeroes you're sending GuideGuide into an infinite loop calculation. That's definitely something that should be prevent within GuideGuide (I'll open an issue for that), but can be avoided by not filling those zero values in.

**Comment by lance1572** [comment]
Ahh I see. I watched a video on youtube on this and that's what the person did. So I just followed along.

thank you!!!

https://youtu.be/zFSI5SpG_eo

**Comment by lance1572** [comment]
Hey Cameron! I think you had already answered the question ;)

On Wed, Dec 9, 2015 at 3:23 PM, Cameron McEfee <notifications@github.com>
wrote:

> Closed #99 <https://github.com/guideguide/support/issues/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guideguide/support/issues/99#event-487383773>.
>



-- 

Lance Nickel
Vice President - Sr Interactive Development Director
809 Gleneagles Court, Suite 111
Baltimore, Maryland 21286
443-279-2010

<http://harborsidegroup.com>

**Comment by cameronmcefee** [comment]
@lance1572 Yep, I just forgot to close the issue. Sorry for the inbox noise.
